"""
Law LLM — Pakistani Legal Assistant
Streamlit Chat Interface
=========================
A chat-style web application that lets users ask questions about
Pakistani law (PPC, CrPC, Constitution) and receive grounded,
cited answers generated by the RAG pipeline.

Features:
  - Chat-style input and conversation history
  - Disclaimer banner on first load
  - Spinner / loading indicator while the pipeline runs
  - Per-answer source metadata display
  - Session-based conversation memory
"""

import sys
import os
from pathlib import Path

import streamlit as st

# Make sibling scripts importable regardless of working directory
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from rag_pipeline import run_rag_pipeline  # noqa: E402

# ---------------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Law LLM — Pakistani Legal Assistant",
    page_icon="⚖️",
    layout="centered",
)

# ---------------------------------------------------------------------------
# Custom CSS — minimal, readable styling
# ---------------------------------------------------------------------------
st.markdown(
    """
    <style>
        /* Main title */
        h1 { color: #1a1a2e; }

        /* User message bubble */
        .user-bubble {
            background-color: #e8f4fd;
            border-left: 4px solid #2196F3;
            padding: 10px 14px;
            border-radius: 8px;
            margin-bottom: 8px;
            font-size: 0.97rem;
        }

        /* Assistant message bubble */
        .assistant-bubble {
            background-color: #f4f9f4;
            border-left: 4px solid #4CAF50;
            padding: 10px 14px;
            border-radius: 8px;
            margin-bottom: 16px;
            font-size: 0.97rem;
        }

        /* Source badge */
        .source-badge {
            font-size: 0.75rem;
            color: #666;
            margin-top: 4px;
        }

        /* Disclaimer box */
        .disclaimer {
            background-color: #fff8e1;
            border: 1px solid #ffcc02;
            border-radius: 6px;
            padding: 10px 14px;
            font-size: 0.85rem;
            color: #555;
            margin-bottom: 20px;
        }
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------
st.title("⚖️ Law LLM — Pakistani Legal Assistant")
st.caption(
    "Ask questions about the Pakistan Penal Code, Code of Criminal Procedure, "
    "or the Constitution of Pakistan."
)

# ---------------------------------------------------------------------------
# Disclaimer banner (shown once per session)
# ---------------------------------------------------------------------------
if "disclaimer_accepted" not in st.session_state:
    st.session_state.disclaimer_accepted = False

if not st.session_state.disclaimer_accepted:
    st.markdown(
        """
        <div class="disclaimer">
        ⚠️ <strong>Disclaimer:</strong> This tool is for informational and academic purposes only.
        It is <strong>not a substitute for professional legal advice</strong>.
        Answers are generated from a curated legal database and may not reflect
        the most recent amendments. Always consult a qualified lawyer for legal matters.
        </div>
        """,
        unsafe_allow_html=True,
    )
    if st.button("I understand — continue", key="accept_disclaimer"):
        st.session_state.disclaimer_accepted = True
        st.rerun()
    st.stop()   # Block the rest of the UI until disclaimer is accepted

# ---------------------------------------------------------------------------
# Session state — conversation history
# ---------------------------------------------------------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []   # List of {"role": ..., "content": ..., "sources": ...}

# ---------------------------------------------------------------------------
# Render conversation history
# ---------------------------------------------------------------------------
for msg in st.session_state.messages:
    if msg["role"] == "user":
        st.markdown(
            f'<div class="user-bubble">🧑 <strong>You:</strong> {msg["content"]}</div>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            f'<div class="assistant-bubble">⚖️ <strong>Assistant:</strong><br>{msg["content"]}</div>',
            unsafe_allow_html=True,
        )
        # Display retrieved source metadata if available
        if msg.get("sources"):
            with st.expander("📄 Sources retrieved", expanded=False):
                for i, src in enumerate(msg["sources"], 1):
                    st.markdown(f"**{i}.** {src}")

# ---------------------------------------------------------------------------
# Chat input box
# ---------------------------------------------------------------------------
st.divider()
user_input = st.chat_input("Ask a legal question about Pakistani law...")

if user_input:
    # Append user message to history
    st.session_state.messages.append({"role": "user", "content": user_input})

    # Show a loading spinner while the RAG pipeline runs
    with st.spinner("Searching legal database and generating answer..."):
        try:
            answer, retrieved_docs = run_rag_pipeline(user_input)

            # Build source labels from retrieved chunk text snippets (first 80 chars each)
            source_labels = [
                f"Chunk {i + 1}: {doc[:80].strip()}..."
                for i, doc in enumerate(retrieved_docs)
            ]
        except Exception as e:
            answer = (
                "Sorry, an error occurred while processing your question. "
                f"Details: {str(e)}"
            )
            source_labels = []

    # Append assistant response to history
    st.session_state.messages.append(
        {"role": "assistant", "content": answer, "sources": source_labels}
    )

    # Rerun to render the updated conversation
    st.rerun()

# ---------------------------------------------------------------------------
# Sidebar — quick info
# ---------------------------------------------------------------------------
with st.sidebar:
    st.header("ℹ️ About")
    st.markdown(
        """
        **Law LLM** is a Retrieval-Augmented Generation (RAG) system
        built for Pakistani law.

        **Sources covered:**
        - 🔵 Pakistan Penal Code (PPC), 1860
        - 🟢 Constitution of Pakistan, 1973
        - 🟡 Code of Criminal Procedure (CrPC), 1898

        **How it works:**
        1. Your question is encoded into a vector
        2. The closest legal text chunks are retrieved from ChromaDB
        3. Retrieved context is injected into a structured prompt
        4. Llama 3.3 70B generates a grounded, cited answer

        **Model:** Llama 3.3 70B via Groq API
        """
    )
    st.divider()

    # Button to clear conversation history
    if st.button("🗑️ Clear conversation", key="clear_chat"):
        st.session_state.messages = []
        st.rerun()

    st.caption("FAST-NUCES Lahore — FYP 2026")
